// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260210154427_Deal")]
    partial class Deal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Booking.BookingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("total_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_booking");

                    b.ToTable("booking", (string)null);
                });

            modelBuilder.Entity("Domain.Customers.Buyer.BuyerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.HasKey("Id")
                        .HasName("pk_buyers");

                    b.ToTable("buyers", (string)null);
                });

            modelBuilder.Entity("Domain.Customers.Client.ClientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Domain.Customers.Seller.SellerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("pk_sellers");

                    b.ToTable("sellers", (string)null);
                });

            modelBuilder.Entity("Domain.Deal.CompletedDealEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyerClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_client_id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DealAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("deal_amount");

                    b.Property<DateTime>("DealDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deal_date");

                    b.Property<string>("DealType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("deal_type");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("SellerClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_client_id");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_completed_deals");

                    b.ToTable("completed_deals", (string)null);
                });

            modelBuilder.Entity("Domain.Deal.DealEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_deals");

                    b.ToTable("deals", (string)null);
                });

            modelBuilder.Entity("Domain.Property.PropertyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_property");

                    b.ToTable("property", (string)null);
                });

            modelBuilder.Entity("Domain.Booking.BookingEntity", b =>
                {
                    b.OwnsOne("Domain.Booking.VO.Period", "BookingPeriod", b1 =>
                        {
                            b1.Property<Guid>("BookingEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("end_date");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("start_date");

                            b1.HasKey("BookingEntityId");

                            b1.ToTable("booking");

                            b1.WithOwner()
                                .HasForeignKey("BookingEntityId");
                        });

                    b.Navigation("BookingPeriod")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Customers.Buyer.BuyerEntity", b =>
                {
                    b.OwnsOne("Domain.Customers.Client.VO.ClientSearchCriteria", "SearchCriteria", b1 =>
                        {
                            b1.Property<Guid>("BuyerEntityId")
                                .HasColumnType("uuid");

                            b1.Property<bool?>("PreferParking")
                                .HasColumnType("boolean")
                                .HasColumnName("prefer_parking");

                            b1.Property<string>("PreferredCondition")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("preferred_condition");

                            b1.Property<int>("PreferredFloor")
                                .HasColumnType("integer")
                                .HasColumnName("preferred_floor");

                            b1.Property<string>("PreferredHeatingType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("preferred_heating_type");

                            b1.Property<int>("PreferredNumberOfRooms")
                                .HasColumnType("integer")
                                .HasColumnName("preferred_number_of_rooms");

                            b1.Property<int>("PreferredTotalFloors")
                                .HasColumnType("integer")
                                .HasColumnName("preferred_total_floors");

                            b1.Property<string>("PreferredType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("preferred_type");

                            b1.HasKey("BuyerEntityId");

                            b1.ToTable("buyers");

                            b1.WithOwner()
                                .HasForeignKey("BuyerEntityId");
                        });

                    b.Navigation("SearchCriteria")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Customers.Client.ClientEntity", b =>
                {
                    b.OwnsOne("Domain.Customers.Client.VO.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<Guid>("ClientEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("email");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("phone_number");

                            b1.HasKey("ClientEntityId");

                            b1.ToTable("clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientEntityId");
                        });

                    b.Navigation("ContactInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Customers.Seller.SellerEntity", b =>
                {
                    b.OwnsMany("Domain.Property.VO.PropertyId", "_ownedProperties", b1 =>
                        {
                            b1.Property<Guid>("seller_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("property_id");

                            b1.HasKey("seller_id", "Value");

                            b1.ToTable("seller_properties", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("seller_id");
                        });

                    b.Navigation("_ownedProperties");
                });

            modelBuilder.Entity("Domain.Deal.DealEntity", b =>
                {
                    b.OwnsOne("Domain.Deal.VO.DealDetails", "Details", b1 =>
                        {
                            b1.Property<Guid>("DealEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Comments")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("comments");

                            b1.Property<decimal>("DealAmount")
                                .HasColumnType("numeric")
                                .HasColumnName("deal_amount");

                            b1.Property<DateTime>("DealDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deal_date");

                            b1.Property<string>("DealType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("deal_type");

                            b1.HasKey("DealEntityId");

                            b1.ToTable("deals");

                            b1.WithOwner()
                                .HasForeignKey("DealEntityId");
                        });

                    b.OwnsMany("Domain.Deal.VO.Document", "Documents", b1 =>
                        {
                            b1.Property<Guid>("deal_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("document_id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("DocumentType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("document_type");

                            b1.Property<string>("FilePath")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("file_path");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("title");

                            b1.HasKey("deal_id", "Id");

                            b1.ToTable("deal_documents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("deal_id");
                        });

                    b.Navigation("Details")
                        .IsRequired();

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Domain.Property.PropertyEntity", b =>
                {
                    b.OwnsOne("Domain.Property.VO.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("PropertyEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("country");

                            b1.Property<int>("HomeNumber")
                                .HasColumnType("integer")
                                .HasColumnName("home_number");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("street");

                            b1.Property<int>("ZipCode")
                                .HasColumnType("integer")
                                .HasColumnName("zip_code");

                            b1.HasKey("PropertyEntityId");

                            b1.ToTable("property");

                            b1.WithOwner()
                                .HasForeignKey("PropertyEntityId");
                        });

                    b.OwnsOne("Domain.Property.VO.OwnershipHistory", "_ownershipHistory", b1 =>
                        {
                            b1.Property<Guid>("PropertyEntityId")
                                .HasColumnType("uuid");

                            b1.HasKey("PropertyEntityId");

                            b1.ToTable("property");

                            b1.WithOwner()
                                .HasForeignKey("PropertyEntityId");

                            b1.OwnsMany("Domain.Property.VO.OwnershipRecord", "Records", b2 =>
                                {
                                    b2.Property<Guid>("property_id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasColumnName("id");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<DateTime?>("EndDate")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("end_date");

                                    b2.Property<Guid>("OwnerClientId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("client_id");

                                    b2.Property<DateTime>("StartDate")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("start_date");

                                    b2.HasKey("property_id", "Id");

                                    b2.ToTable("property_ownership_history", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("property_id");
                                });

                            b1.Navigation("Records");
                        });

                    b.OwnsOne("Domain.Property.VO.PropertyDetails", "PropertyDetails", b1 =>
                        {
                            b1.Property<Guid>("PropertyEntityId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Area")
                                .HasColumnType("numeric")
                                .HasColumnName("area");

                            b1.Property<string>("Condition")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("condition");

                            b1.Property<int>("Floor")
                                .HasColumnType("integer")
                                .HasColumnName("floor");

                            b1.Property<bool>("HasBalcony")
                                .HasColumnType("boolean")
                                .HasColumnName("has_balcony");

                            b1.Property<bool>("HasParking")
                                .HasColumnType("boolean")
                                .HasColumnName("has_parking");

                            b1.Property<string>("HeatingType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("heating_type");

                            b1.Property<int>("NumberOfRooms")
                                .HasColumnType("integer")
                                .HasColumnName("number_of_rooms");

                            b1.Property<int>("TotalFloors")
                                .HasColumnType("integer")
                                .HasColumnName("total_floors");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("property_type");

                            b1.HasKey("PropertyEntityId");

                            b1.ToTable("property");

                            b1.WithOwner()
                                .HasForeignKey("PropertyEntityId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("PropertyDetails")
                        .IsRequired();

                    b.Navigation("_ownershipHistory")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
